# Site settings
title: Electronic Sports Infinity Games
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Electronic Sports Infinity Games
user_description:
user_title: Disfruta de la experiencia gaming definitiva..
email: electronicsportsinfinitygames@gmail.com
twitter_username: lorem_ipsum
instagram_username: lorem_ipsum
facebook_username: ElectronicSportsInfinityGames/
linkedin_username: lorem_ipsum
github_username:  lorem_ipsum
medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

